apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: colorgateway-vn
  namespace: color
spec:
  podSelector:
    matchLabels:
      app: colorgateway
      version: v1
  listeners:
    - portMapping:
        port: 9080
        protocol: http
  serviceDiscovery:
    dns:
      hostname: colorgateway.color.svc.cluster.local
  backends:
    - virtualService:
        virtualServiceName: colorteller.color.svc.cluster.local
