apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: colorteller-black-vn
  namespace: color
spec:
  listeners:
    - portMapping:
        port: 9080
        protocol: http
  serviceDiscovery:
    dns:
      hostname: colorteller-black.color.svc.cluster.local