apiVersion: appmesh.k8s.aws/v1beta2
kind: Route
metadata:
  name: colorteller-route
  namespace : color
spec:
  httpRoute:
    action:
      weightedTargets:
        - virtualNode: colorteller-vn
          weight: 1
    match:
      prefix: "/"
  virtualRouterName: colorteller-vr